version: "3"
services:
  hub: 
    image: selenium/hub:3.14
    container_name: seleniumHub
    ports:
      - "4444:4444"
  firefox: 
    image: selenium/node-firefox:3.14
    container_name: seleniumFirefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  chrome:
    image: selenium/node-chrome:3.14
    container_name: seleniumChrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
